// Code generated by protoc-gen-go. DO NOT EDIT.
// source: scaler-api.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Containers struct {
	Container            []*Container `protobuf:"bytes,1,rep,name=container,proto3" json:"container,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Containers) Reset()         { *m = Containers{} }
func (m *Containers) String() string { return proto.CompactTextString(m) }
func (*Containers) ProtoMessage()    {}
func (*Containers) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e55e8ce18b80753, []int{0}
}

func (m *Containers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Containers.Unmarshal(m, b)
}
func (m *Containers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Containers.Marshal(b, m, deterministic)
}
func (m *Containers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Containers.Merge(m, src)
}
func (m *Containers) XXX_Size() int {
	return xxx_messageInfo_Containers.Size(m)
}
func (m *Containers) XXX_DiscardUnknown() {
	xxx_messageInfo_Containers.DiscardUnknown(m)
}

var xxx_messageInfo_Containers proto.InternalMessageInfo

func (m *Containers) GetContainer() []*Container {
	if m != nil {
		return m.Container
	}
	return nil
}

type Container struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Names                []string `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	Image                string   `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e55e8ce18b80753, []int{1}
}

func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (m *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(m, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Container) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

func (m *Container) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

type ContainerId struct {
	ContainerId          string   `protobuf:"bytes,1,opt,name=containerId,proto3" json:"containerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainerId) Reset()         { *m = ContainerId{} }
func (m *ContainerId) String() string { return proto.CompactTextString(m) }
func (*ContainerId) ProtoMessage()    {}
func (*ContainerId) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e55e8ce18b80753, []int{2}
}

func (m *ContainerId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerId.Unmarshal(m, b)
}
func (m *ContainerId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerId.Marshal(b, m, deterministic)
}
func (m *ContainerId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerId.Merge(m, src)
}
func (m *ContainerId) XXX_Size() int {
	return xxx_messageInfo_ContainerId.Size(m)
}
func (m *ContainerId) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerId.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerId proto.InternalMessageInfo

func (m *ContainerId) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

type ContainerConfig struct {
	Image                string   `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainerConfig) Reset()         { *m = ContainerConfig{} }
func (m *ContainerConfig) String() string { return proto.CompactTextString(m) }
func (*ContainerConfig) ProtoMessage()    {}
func (*ContainerConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e55e8ce18b80753, []int{3}
}

func (m *ContainerConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerConfig.Unmarshal(m, b)
}
func (m *ContainerConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerConfig.Marshal(b, m, deterministic)
}
func (m *ContainerConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerConfig.Merge(m, src)
}
func (m *ContainerConfig) XXX_Size() int {
	return xxx_messageInfo_ContainerConfig.Size(m)
}
func (m *ContainerConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerConfig proto.InternalMessageInfo

func (m *ContainerConfig) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

type ContainerStat struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainerStat) Reset()         { *m = ContainerStat{} }
func (m *ContainerStat) String() string { return proto.CompactTextString(m) }
func (*ContainerStat) ProtoMessage()    {}
func (*ContainerStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e55e8ce18b80753, []int{4}
}

func (m *ContainerStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerStat.Unmarshal(m, b)
}
func (m *ContainerStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerStat.Marshal(b, m, deterministic)
}
func (m *ContainerStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerStat.Merge(m, src)
}
func (m *ContainerStat) XXX_Size() int {
	return xxx_messageInfo_ContainerStat.Size(m)
}
func (m *ContainerStat) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerStat.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerStat proto.InternalMessageInfo

func (m *ContainerStat) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Project struct {
	Image                string   `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Min                  int32    `protobuf:"varint,2,opt,name=min,proto3" json:"min,omitempty"`
	Max                  int32    `protobuf:"varint,3,opt,name=max,proto3" json:"max,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Cpu                  float32  `protobuf:"fixed32,5,opt,name=cpu,proto3" json:"cpu,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e55e8ce18b80753, []int{5}
}

func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (m *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(m, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Project) GetMin() int32 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *Project) GetMax() int32 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *Project) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Project) GetCpu() float32 {
	if m != nil {
		return m.Cpu
	}
	return 0
}

type ProjectInfo struct {
	ContainerId          []string `protobuf:"bytes,1,rep,name=containerId,proto3" json:"containerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProjectInfo) Reset()         { *m = ProjectInfo{} }
func (m *ProjectInfo) String() string { return proto.CompactTextString(m) }
func (*ProjectInfo) ProtoMessage()    {}
func (*ProjectInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e55e8ce18b80753, []int{6}
}

func (m *ProjectInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectInfo.Unmarshal(m, b)
}
func (m *ProjectInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectInfo.Marshal(b, m, deterministic)
}
func (m *ProjectInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectInfo.Merge(m, src)
}
func (m *ProjectInfo) XXX_Size() int {
	return xxx_messageInfo_ProjectInfo.Size(m)
}
func (m *ProjectInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectInfo proto.InternalMessageInfo

func (m *ProjectInfo) GetContainerId() []string {
	if m != nil {
		return m.ContainerId
	}
	return nil
}

type StopProjectRequest struct {
	ProjectName          string   `protobuf:"bytes,1,opt,name=projectName,proto3" json:"projectName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopProjectRequest) Reset()         { *m = StopProjectRequest{} }
func (m *StopProjectRequest) String() string { return proto.CompactTextString(m) }
func (*StopProjectRequest) ProtoMessage()    {}
func (*StopProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e55e8ce18b80753, []int{7}
}

func (m *StopProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopProjectRequest.Unmarshal(m, b)
}
func (m *StopProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopProjectRequest.Marshal(b, m, deterministic)
}
func (m *StopProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopProjectRequest.Merge(m, src)
}
func (m *StopProjectRequest) XXX_Size() int {
	return xxx_messageInfo_StopProjectRequest.Size(m)
}
func (m *StopProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopProjectRequest proto.InternalMessageInfo

func (m *StopProjectRequest) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

type StopProjectResponse struct {
	ContainerID          []string `protobuf:"bytes,1,rep,name=containerID,proto3" json:"containerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopProjectResponse) Reset()         { *m = StopProjectResponse{} }
func (m *StopProjectResponse) String() string { return proto.CompactTextString(m) }
func (*StopProjectResponse) ProtoMessage()    {}
func (*StopProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e55e8ce18b80753, []int{8}
}

func (m *StopProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopProjectResponse.Unmarshal(m, b)
}
func (m *StopProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopProjectResponse.Marshal(b, m, deterministic)
}
func (m *StopProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopProjectResponse.Merge(m, src)
}
func (m *StopProjectResponse) XXX_Size() int {
	return xxx_messageInfo_StopProjectResponse.Size(m)
}
func (m *StopProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopProjectResponse proto.InternalMessageInfo

func (m *StopProjectResponse) GetContainerID() []string {
	if m != nil {
		return m.ContainerID
	}
	return nil
}

func init() {
	proto.RegisterType((*Containers)(nil), "v1.containers")
	proto.RegisterType((*Container)(nil), "v1.container")
	proto.RegisterType((*ContainerId)(nil), "v1.containerId")
	proto.RegisterType((*ContainerConfig)(nil), "v1.containerConfig")
	proto.RegisterType((*ContainerStat)(nil), "v1.containerStat")
	proto.RegisterType((*Project)(nil), "v1.project")
	proto.RegisterType((*ProjectInfo)(nil), "v1.projectInfo")
	proto.RegisterType((*StopProjectRequest)(nil), "v1.StopProjectRequest")
	proto.RegisterType((*StopProjectResponse)(nil), "v1.StopProjectResponse")
}

func init() { proto.RegisterFile("scaler-api.proto", fileDescriptor_4e55e8ce18b80753) }

var fileDescriptor_4e55e8ce18b80753 = []byte{
	// 453 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xd1, 0x8a, 0xd3, 0x40,
	0x14, 0x25, 0xc9, 0x56, 0xe9, 0x2d, 0xed, 0xd6, 0x5b, 0x59, 0x43, 0x7c, 0x09, 0xf1, 0xc1, 0x80,
	0x6c, 0x6a, 0xbb, 0xe8, 0x22, 0x82, 0x2f, 0xae, 0x48, 0x41, 0x44, 0xd2, 0x2f, 0x98, 0x4d, 0x6f,
	0xcb, 0xc8, 0x26, 0x13, 0x33, 0xd3, 0xb2, 0xfe, 0xa2, 0x5f, 0x25, 0x93, 0xc4, 0x64, 0x66, 0xe3,
	0xc3, 0xbe, 0xcd, 0x3d, 0x73, 0xee, 0xb9, 0x73, 0xe7, 0x1c, 0x98, 0xcb, 0x8c, 0xdd, 0x51, 0x75,
	0xc9, 0x4a, 0x9e, 0x94, 0x95, 0x50, 0x02, 0xdd, 0xd3, 0x2a, 0x78, 0x79, 0x10, 0xe2, 0x70, 0x47,
	0xcb, 0x1a, 0xb9, 0x3d, 0xee, 0x97, 0x94, 0x97, 0xea, 0x77, 0x43, 0x88, 0x3e, 0x00, 0x64, 0xa2,
	0x50, 0x8c, 0x17, 0x54, 0x49, 0x7c, 0x03, 0xe3, 0xae, 0xf2, 0x9d, 0xd0, 0x8b, 0x27, 0xeb, 0x69,
	0x72, 0x5a, 0x25, 0x1d, 0x98, 0xf6, 0xf7, 0xd1, 0x57, 0x83, 0x8c, 0x33, 0x70, 0xf9, 0xce, 0x77,
	0x42, 0x27, 0x1e, 0xa7, 0x2e, 0xdf, 0xe1, 0x73, 0x18, 0x15, 0x2c, 0x27, 0xe9, 0xbb, 0xa1, 0x17,
	0x8f, 0xd3, 0xa6, 0xd0, 0x28, 0xcf, 0xd9, 0x81, 0x7c, 0xaf, 0x26, 0x36, 0x45, 0xb4, 0x84, 0x49,
	0x27, 0xb4, 0xd9, 0x61, 0x68, 0x95, 0xad, 0xa6, 0x09, 0x45, 0xaf, 0xe1, 0xbc, 0x2b, 0x3f, 0x8b,
	0x62, 0xcf, 0x0f, 0xbd, 0xb2, 0x63, 0x2a, 0xbf, 0x82, 0x69, 0x47, 0xdc, 0x2a, 0xa6, 0x10, 0xe1,
	0x4c, 0xbf, 0xa4, 0x65, 0xd5, 0xe7, 0x88, 0xc3, 0xd3, 0xb2, 0x12, 0x3f, 0x29, 0x53, 0xff, 0x57,
	0xc1, 0x39, 0x78, 0x39, 0x2f, 0x7c, 0x37, 0x74, 0xe2, 0x51, 0xaa, 0x8f, 0x35, 0xc2, 0xee, 0xeb,
	0x2d, 0x34, 0xc2, 0xee, 0x3b, 0xe1, 0xb3, 0x5e, 0x58, 0xb3, 0xb2, 0xf2, 0xe8, 0x8f, 0x42, 0x27,
	0x76, 0x53, 0x7d, 0xd4, 0x9b, 0xb6, 0xa3, 0x36, 0xc5, 0x5e, 0x0c, 0x37, 0xf5, 0x1e, 0x6e, 0xfa,
	0x1e, 0x70, 0xab, 0x44, 0xf9, 0xa3, 0x69, 0x4a, 0xe9, 0xd7, 0x91, 0xa4, 0xd2, 0x7d, 0xad, 0xcc,
	0xf7, 0x7e, 0x19, 0x13, 0x8a, 0xae, 0x61, 0x61, 0xf5, 0xc9, 0x52, 0x14, 0x92, 0xec, 0x81, 0x37,
	0xc3, 0x81, 0x37, 0xeb, 0x3f, 0x1e, 0xcc, 0xfb, 0x2f, 0xa3, 0xea, 0xc4, 0x33, 0xc2, 0x6b, 0xe3,
	0x1b, 0xbf, 0x71, 0xa9, 0xf0, 0x22, 0x69, 0x32, 0x95, 0xfc, 0xcb, 0x54, 0xf2, 0x45, 0x67, 0x2a,
	0x98, 0x59, 0x61, 0x91, 0xb8, 0xb2, 0xfe, 0x5f, 0x94, 0x78, 0x6e, 0x11, 0x36, 0xbb, 0xe0, 0x21,
	0x80, 0x6b, 0x98, 0x99, 0x96, 0x55, 0xea, 0x11, 0x3d, 0xef, 0xcc, 0x3c, 0x54, 0xc4, 0x14, 0xe1,
	0xc2, 0xe2, 0x34, 0x21, 0x09, 0xec, 0x2c, 0xe3, 0x95, 0xd1, 0x96, 0x52, 0x2e, 0x4e, 0xf4, 0x88,
	0x59, 0x1f, 0x61, 0x61, 0x45, 0x6a, 0xab, 0x2a, 0x62, 0xf9, 0xb0, 0xf1, 0x99, 0x05, 0x68, 0xe6,
	0x5b, 0x07, 0x2f, 0x61, 0x9a, 0xd5, 0xef, 0x6b, 0x8d, 0xc1, 0x89, 0x66, 0xb5, 0xc6, 0x35, 0xb3,
	0xcc, 0x7c, 0x7c, 0x82, 0x89, 0xec, 0x5d, 0xc4, 0x0b, 0x7d, 0x3f, 0x8c, 0x43, 0xf0, 0x62, 0x80,
	0x37, 0x76, 0xdf, 0x3e, 0xa9, 0xed, 0xb9, 0xfa, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x35, 0x01, 0xb0,
	0x4b, 0x18, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ContainerServiceClient is the client API for ContainerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ContainerServiceClient interface {
	ContainerList(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Containers, error)
	ContainerStop(ctx context.Context, in *ContainerId, opts ...grpc.CallOption) (*ContainerId, error)
	ContainerStart(ctx context.Context, in *ContainerId, opts ...grpc.CallOption) (*ContainerId, error)
	ContainerCreate(ctx context.Context, in *ContainerConfig, opts ...grpc.CallOption) (*Container, error)
	ContainerRemove(ctx context.Context, in *ContainerId, opts ...grpc.CallOption) (*ContainerId, error)
	ContainerStatStream(ctx context.Context, in *ContainerId, opts ...grpc.CallOption) (ContainerService_ContainerStatStreamClient, error)
	CreateProject(ctx context.Context, in *Project, opts ...grpc.CallOption) (*ProjectInfo, error)
	StopProject(ctx context.Context, in *StopProjectRequest, opts ...grpc.CallOption) (*StopProjectResponse, error)
}

type containerServiceClient struct {
	cc *grpc.ClientConn
}

func NewContainerServiceClient(cc *grpc.ClientConn) ContainerServiceClient {
	return &containerServiceClient{cc}
}

func (c *containerServiceClient) ContainerList(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Containers, error) {
	out := new(Containers)
	err := c.cc.Invoke(ctx, "/v1.containerService/containerList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerServiceClient) ContainerStop(ctx context.Context, in *ContainerId, opts ...grpc.CallOption) (*ContainerId, error) {
	out := new(ContainerId)
	err := c.cc.Invoke(ctx, "/v1.containerService/containerStop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerServiceClient) ContainerStart(ctx context.Context, in *ContainerId, opts ...grpc.CallOption) (*ContainerId, error) {
	out := new(ContainerId)
	err := c.cc.Invoke(ctx, "/v1.containerService/containerStart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerServiceClient) ContainerCreate(ctx context.Context, in *ContainerConfig, opts ...grpc.CallOption) (*Container, error) {
	out := new(Container)
	err := c.cc.Invoke(ctx, "/v1.containerService/containerCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerServiceClient) ContainerRemove(ctx context.Context, in *ContainerId, opts ...grpc.CallOption) (*ContainerId, error) {
	out := new(ContainerId)
	err := c.cc.Invoke(ctx, "/v1.containerService/containerRemove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerServiceClient) ContainerStatStream(ctx context.Context, in *ContainerId, opts ...grpc.CallOption) (ContainerService_ContainerStatStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ContainerService_serviceDesc.Streams[0], "/v1.containerService/containerStatStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &containerServiceContainerStatStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ContainerService_ContainerStatStreamClient interface {
	Recv() (*ContainerStat, error)
	grpc.ClientStream
}

type containerServiceContainerStatStreamClient struct {
	grpc.ClientStream
}

func (x *containerServiceContainerStatStreamClient) Recv() (*ContainerStat, error) {
	m := new(ContainerStat)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *containerServiceClient) CreateProject(ctx context.Context, in *Project, opts ...grpc.CallOption) (*ProjectInfo, error) {
	out := new(ProjectInfo)
	err := c.cc.Invoke(ctx, "/v1.containerService/createProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerServiceClient) StopProject(ctx context.Context, in *StopProjectRequest, opts ...grpc.CallOption) (*StopProjectResponse, error) {
	out := new(StopProjectResponse)
	err := c.cc.Invoke(ctx, "/v1.containerService/stopProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContainerServiceServer is the server API for ContainerService service.
type ContainerServiceServer interface {
	ContainerList(context.Context, *empty.Empty) (*Containers, error)
	ContainerStop(context.Context, *ContainerId) (*ContainerId, error)
	ContainerStart(context.Context, *ContainerId) (*ContainerId, error)
	ContainerCreate(context.Context, *ContainerConfig) (*Container, error)
	ContainerRemove(context.Context, *ContainerId) (*ContainerId, error)
	ContainerStatStream(*ContainerId, ContainerService_ContainerStatStreamServer) error
	CreateProject(context.Context, *Project) (*ProjectInfo, error)
	StopProject(context.Context, *StopProjectRequest) (*StopProjectResponse, error)
}

func RegisterContainerServiceServer(s *grpc.Server, srv ContainerServiceServer) {
	s.RegisterService(&_ContainerService_serviceDesc, srv)
}

func _ContainerService_ContainerList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerServiceServer).ContainerList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.containerService/ContainerList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerServiceServer).ContainerList(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerService_ContainerStop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerServiceServer).ContainerStop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.containerService/ContainerStop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerServiceServer).ContainerStop(ctx, req.(*ContainerId))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerService_ContainerStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerServiceServer).ContainerStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.containerService/ContainerStart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerServiceServer).ContainerStart(ctx, req.(*ContainerId))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerService_ContainerCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerServiceServer).ContainerCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.containerService/ContainerCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerServiceServer).ContainerCreate(ctx, req.(*ContainerConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerService_ContainerRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerServiceServer).ContainerRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.containerService/ContainerRemove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerServiceServer).ContainerRemove(ctx, req.(*ContainerId))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerService_ContainerStatStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ContainerId)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ContainerServiceServer).ContainerStatStream(m, &containerServiceContainerStatStreamServer{stream})
}

type ContainerService_ContainerStatStreamServer interface {
	Send(*ContainerStat) error
	grpc.ServerStream
}

type containerServiceContainerStatStreamServer struct {
	grpc.ServerStream
}

func (x *containerServiceContainerStatStreamServer) Send(m *ContainerStat) error {
	return x.ServerStream.SendMsg(m)
}

func _ContainerService_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Project)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerServiceServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.containerService/CreateProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerServiceServer).CreateProject(ctx, req.(*Project))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerService_StopProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerServiceServer).StopProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.containerService/StopProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerServiceServer).StopProject(ctx, req.(*StopProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ContainerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.containerService",
	HandlerType: (*ContainerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "containerList",
			Handler:    _ContainerService_ContainerList_Handler,
		},
		{
			MethodName: "containerStop",
			Handler:    _ContainerService_ContainerStop_Handler,
		},
		{
			MethodName: "containerStart",
			Handler:    _ContainerService_ContainerStart_Handler,
		},
		{
			MethodName: "containerCreate",
			Handler:    _ContainerService_ContainerCreate_Handler,
		},
		{
			MethodName: "containerRemove",
			Handler:    _ContainerService_ContainerRemove_Handler,
		},
		{
			MethodName: "createProject",
			Handler:    _ContainerService_CreateProject_Handler,
		},
		{
			MethodName: "stopProject",
			Handler:    _ContainerService_StopProject_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "containerStatStream",
			Handler:       _ContainerService_ContainerStatStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "scaler-api.proto",
}
